# -*- coding: utf-8 -*-
"""exercicio_4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnE0Z5gjTygI-R1MIxT5JC0DWT1HqAdW
"""

notas = [7.5, 8.0, 6.0, 9.5, 5.5, 8.5, 7.0, 9.0, 6.5, 8.0]
nomes = ['Carlos', 'Ana', 'Bruno', 'Ana', 'Diego', 'Ana', 'Bruno']

print("Listas inicializadas:")
print(f"Notas: {notas}")
print(f"Nomes: {nomes}")

media_notas = sum(notas) / len(notas)
print(f"A média das notas é: {media_notas:.2f}")

maior_nota = max(notas)
menor_nota = min(notas)

alunos_acima_media = 0
for nota in notas:
    if nota > media_notas:
        alunos_acima_media += 1

print(f"A maior nota é: {maior_nota}")
print(f"A menor nota é: {menor_nota}")
print(f"Número de alunos acima da média: {alunos_acima_media}")

contagem_ana = nomes.count('Ana')
print(f"'Ana' aparece {contagem_ana} vezes na lista de nomes.")

indice_bruno = nomes.index('Bruno')
print(f"'Bruno' aparece pela primeira vez no índice: {indice_bruno}")

nomes_sem_repeticao = []
for nome in nomes:
    if nome not in nomes_sem_repeticao:
        nomes_sem_repeticao.append(nome)

print(f"Lista de nomes sem repetição (mantendo a ordem): {nomes_sem_repeticao}")